"""Regenerate original synthetic PDFs and provenance, without human labels."""
import hashlib
import json
from pathlib import Path
from io import BytesIO
from pypdf import PdfWriter
from pypdf.generic import DictionaryObject, NameObject, DecodedStreamObject


def pdf(texts):
    writer = PdfWriter()
    for text in texts:
        page = writer.add_blank_page(width=600, height=800)
        font = DictionaryObject({NameObject('/Type'): NameObject('/Font'), NameObject('/Subtype'): NameObject('/Type1'), NameObject('/BaseFont'): NameObject('/Helvetica')})
        page[NameObject('/Resources')] = DictionaryObject({NameObject('/Font'): DictionaryObject({NameObject('/F1'): writer._add_object(font)})})
        stream = DecodedStreamObject()
        stream.set_data(('BT /F1 12 Tf 40 700 Td (' + text + ') Tj ET').encode('ascii'))
        page[NameObject('/Contents')] = writer._add_object(stream)
    output = BytesIO()
    writer.write(output)
    return output.getvalue()


def main():
    root = Path(__file__).parent
    cases = [
        ('normal', ['We propose a compact algorithm. Results show a measured increase. A second method is described here.'], 50, ['method', 'result']),
        ('empty_text', [''], 50, []),
        ('truncated', ['We propose a compact algorithm.', 'Results show a measured increase.'], 1, ['method']),
        ('absent_experiments', ['This essay describes the history of scientific writing.'], 50, []),
        ('planned_experiments', ['We plan experiments for future work.'], 50, ['future_work']),
        ('unsupported_quote', ['We propose a compact algorithm.'], 50, ['method']),
    ]
    records = []
    for name, pages, limit, categories in cases:
        data = pdf(pages)
        (root / f'{name}.pdf').write_bytes(data)
        annotations = []
        if name != 'empty_text':
            for sentence, category in zip(pages[0].split('. ') if name == 'normal' else pages, categories):
                annotations.append(dict(page=1, quote=sentence.rstrip('.') + '.', category=category, supported=True))
        records.append(dict(id=name, file=f'{name}.pdf', sha256=hashlib.sha256(data).hexdigest(),
                            source=f'original-synthetic:{name}', license='CC0-1.0',
                            provenance='Original AI-authored synthetic text and PDF; generated by generate.py, adapted from tests/test_evidence_pdf.py; no external paper content.',
                            status='pending_human_review', reviewer=None, reviewed_at=None,
                            max_pages=limit, annotations=annotations,
                            expected_categories=categories, expected_truncated=name == 'truncated',
                            expected_error=name == 'empty_text', reject_quote='Invented accuracy is ninety nine percent.' if name == 'unsupported_quote' else None))
    (root / 'manifest.json').write_text(json.dumps(dict(schema_version=1, records=records), indent=2) + '\n', encoding='utf-8')


if __name__ == '__main__':
    main()
