"""Regenerate original synthetic PDFs and provenance, without human labels."""
import argparse
import hashlib
import json
from pathlib import Path
from io import BytesIO
from pypdf import PdfWriter
from pypdf.generic import DictionaryObject, NameObject, DecodedStreamObject, NumberObject


def pdf(texts):
    writer = PdfWriter()
    for text in texts:
        page = writer.add_blank_page(width=600, height=800)
        font = DictionaryObject({NameObject('/Type'): NameObject('/Font'), NameObject('/Subtype'): NameObject('/Type1'), NameObject('/BaseFont'): NameObject('/Helvetica')})
        page[NameObject('/Resources')] = DictionaryObject({NameObject('/Font'): DictionaryObject({NameObject('/F1'): writer._add_object(font)})})
        stream = DecodedStreamObject()
        stream.set_data(('BT /F1 12 Tf 40 700 Td (' + text + ') Tj ET').encode('ascii'))
        page[NameObject('/Contents')] = writer._add_object(stream)
    output = BytesIO()
    writer.write(output)
    return output.getvalue()


def image_pdf():
    """Original raster-only page: simulated scan, no OCR/text layer or external image."""
    writer = PdfWriter()
    page = writer.add_blank_page(width=600, height=800)
    image = DecodedStreamObject()
    image.set_data(bytes(35 if 3 <= x < 28 and y in (3, 4, 7, 8, 11) else 255
                         for y in range(16) for x in range(32)))
    image.update({NameObject('/Type'): NameObject('/XObject'),
                  NameObject('/Subtype'): NameObject('/Image'),
                  NameObject('/Width'): NumberObject(32),
                  NameObject('/Height'): NumberObject(16),
                  NameObject('/ColorSpace'): NameObject('/DeviceGray'),
                  NameObject('/BitsPerComponent'): NumberObject(8)})
    page[NameObject('/Resources')] = DictionaryObject({NameObject('/XObject'):
        DictionaryObject({NameObject('/Scan'): writer._add_object(image)})})
    stream = DecodedStreamObject()
    stream.set_data(b'q 480 0 0 240 60 480 cm /Scan Do Q')
    page[NameObject('/Contents')] = writer._add_object(stream)
    output = BytesIO()
    writer.write(output)
    return output.getvalue()


def generate(root):
    root = Path(root)
    cases = [
        ('normal', ['We propose a compact algorithm. Results show a measured increase. A second method is described here.'], 50, ['method', 'result']),
        ('empty_text', [''], 50, []),
        ('image_only', [], 50, []),
        ('truncated', ['We propose a compact algorithm.', 'Results show a measured increase.'], 1, ['method']),
        ('absent_experiments', ['This essay describes the history of scientific writing.'], 50, []),
        ('planned_experiments', ['We plan experiments for future work.'], 50, ['future_work']),
        ('unsupported_quote', ['We propose a compact algorithm.'], 50, ['method']),
    ]
    names = ['manifest.json', *(f'{case[0]}.pdf' for case in cases)]
    if any((root / name).exists() for name in names):
        raise FileExistsError('Refusing to overwrite existing corpus files; choose a new --output-dir')
    records = []
    outputs = {}
    for name, pages, limit, categories in cases:
        data = image_pdf() if name == 'image_only' else pdf(pages)
        outputs[f'{name}.pdf'] = data
        annotations = []
        if name not in ('empty_text', 'image_only'):
            for sentence, category in zip(pages[0].split('. ') if name == 'normal' else pages, categories):
                annotations.append(dict(page=1, quote=sentence.rstrip('.') + '.', category=category, supported=True))
        records.append(dict(id=name, file=f'{name}.pdf', sha256=hashlib.sha256(data).hexdigest(),
                            source=f'original-synthetic:{name}', license='CC0-1.0',
                            provenance=('Original algorithmically generated grayscale raster bars simulating an image-only scan; no text layer, external image, or published research content.' if name == 'image_only' else 'Original AI-authored synthetic text and PDF; generated by generate.py, adapted from tests/test_evidence_pdf.py; no external paper content.'),
                            status='pending_human_review', reviewer=None, reviewed_at=None,
                            max_pages=limit, annotations=annotations,
                            expected_categories=categories, expected_truncated=name == 'truncated',
                            expected_error=name in ('empty_text', 'image_only'), reject_quote='Invented accuracy is ninety nine percent.' if name == 'unsupported_quote' else None))
    outputs['manifest.json'] = (json.dumps(dict(schema_version=1, records=records), indent=2) + '\n').encode('utf-8')
    root.mkdir(parents=True, exist_ok=True)
    for name, data in outputs.items():
        with (root / name).open('xb') as output:
            output.write(data)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output-dir', type=Path, default=Path(__file__).parent,
                        help='Use a fresh directory; existing corpus files are never overwritten')
    args = parser.parse_args()
    try:
        generate(args.output_dir)
    except FileExistsError as exc:
        parser.exit(1, f'{exc}\n')


if __name__ == '__main__':
    main()
